from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction


def calculate_bleu(reference_titles, generated_titles):
    """
    Calculate BLEU score for generated titles.

    Parameters:
    - reference_titles: list, actual titles by the author.
    - generated_titles: list, titles generated by the model.

    Returns:
    - Average BLEU score.
    """
    smoothie = SmoothingFunction().method4
    scores = []
    for ref, gen in zip(reference_titles, generated_titles):
        ref_tokens = ref.lower().split()
        gen_tokens = gen.lower().split()
        score = sentence_bleu([ref_tokens], gen_tokens, smoothing_function=smoothie)
        scores.append(score)
    return sum(scores) / len(scores) if scores else 0.0
