from sentence_transformers import SentenceTransformer, util

# Load a pre-trained transformer model
model = SentenceTransformer('all-MiniLM-L6-v2')

def evaluate_relevance(reference_titles, generated_titles):
    """
    Evaluate relevance using cosine similarity.

    Parameters:
    - reference_titles: list, actual titles by the author.
    - generated_titles: list, titles generated by the model.

    Returns:
    - Average relevance score.
    """
    scores = []
    for ref, gen in zip(reference_titles, generated_titles):
        embeddings = model.encode([ref, gen])
        similarity = util.cos_sim(embeddings[0], embeddings[1]).item()
        scores.append(similarity)
    return sum(scores) / len(scores) if scores else 0.0
