

def evaluate_specificity_diversity(generated_titles):
    """
    Evaluate specificity and diversity of generated titles.

    Parameters:
    - generated_titles: list, titles generated by the model.

    Returns:
    - Specificity: Average length of titles (proxy for detail level).
    - Diversity: Ratio of unique words to total words.
    """
    word_count = sum(len(title.split()) for title in generated_titles)
    unique_words = set(word for title in generated_titles for word in title.split())
    total_words = sum(len(title.split()) for title in generated_titles)

    specificity = word_count / len(generated_titles) if generated_titles else 0.0
    diversity = len(unique_words) / total_words if total_words > 0 else 0.0

    return specificity, diversity



